### ISSUE TITLE
Fix panic

### ISSUE THREAD

**Issue by tw-covain** [KRR19/EthereumParser#1]
```
curl 'localhost:8080/api/v1/transactions?address=0xdac17f958d2ee523a2206206994597c13d831ec7'
____
curl: (52) Empty reply from server
```

Server's logs:
```
2024/12/12 01:10:59 http: panic serving [::1]:60964: runtime error: invalid memory address or nil pointer dereference
goroutine 129 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:1947 +0xb0
panic({0x1029b7160?, 0x102bd99d0?})
        /opt/homebrew/opt/go/libexec/src/runtime/panic.go:785 +0x124
github.com/KRR19/EthereumParser/internal/core.(*ParserService).GetTransactions(0x14000116b40, {0x140000ae2d0?, 0x1028f5b42?}, {0x140002de021?, 0x1400018f9f8?})
 ```

**Comment by KRR19** [comment]
Thank you for reporting this issue! The problem was related to external dependencies, which caused a panic in the GetTransactions method. This has now been identified and resolved. Please pull the latest changes from the repository and try again. Let us know if you encounter any further issues!
